.
        return -1;
      }
      PyErr_SetObject(exception_class, val.get());
      return -1;
    } 