		testAssert("fail gracefully on bad table", !readStatus);
	}
	catch (std::exception