 (const std::exception &e)
    {
	cerr << "ERROR -- caught exception: " << e.what() << e