e_handle::ops, 0);
		testAssert("fail gracefully on bad table", !face);
	}
	catch (std::exception & e)
	{
		fp